apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "elastic-operator.fullname" . }}
  labels:
{{ include "elastic-operator.labels" . | indent 4 }}
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- with .Values.annotations }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "elastic-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      control-plane: {{ include "elastic-operator.name" . }}
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "elastic-operator.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "elastic-operator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        control-plane: {{ include "elastic-operator.name" . }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        "co.elastic.logs/raw": "[{\"type\":\"container\",\"json.keys_under_root\":true,\"paths\":[\"/var/log/containers/*${data.kubernetes.container.id}.log\"],\"processors\":[{\"convert\":{\"mode\":\"rename\",\"ignore_missing\":true,\"fields\":[{\"from\":\"error\",\"to\":\"_error\"}]}},{\"convert\":{\"mode\":\"rename\",\"ignore_missing\":true,\"fields\":[{\"from\":\"_error\",\"to\":\"error.message\"}]}},{\"convert\":{\"mode\":\"rename\",\"ignore_missing\":true,\"fields\":[{\"from\":\"source\",\"to\":\"_source\"}]}},{\"convert\":{\"mode\":\"rename\",\"ignore_missing\":true,\"fields\":[{\"from\":\"_source\",\"to\":\"event.source\"}]}}]}]"
      {{- if .Values.podAnnotations }}
        {{- with .Values.podAnnotations }}
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "elastic-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["manager"]
          env:
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_IMAGE
              value: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            - name: OPERATOR_ROLES
              value: {{ .Values.operator.roles | quote }}
            - name: LOG_VERBOSITY
              value: {{ .Values.operator.logVerbosity | quote }}
            {{- if .Values.operator.metricsPort }}
            - name: METRICS_PORT
              value: {{ .Values.operator.metricsPort | quote}}
            {{- end }}
            {{- if .Values.webhook.enabled }}
            - name: WEBHOOK_SECRET
              value: {{ include "elastic-operator.fullname" . }}-webhook-server-cert
            {{- end }}
          ports:
            - name: webhook-server
              containerPort: 9443
              protocol: TCP
            {{- if .Values.operator.metricsPort }}
            - name: metrics
              containerPort: {{ .Values.operator.metricsPort }}
              protocol: TCP
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.webhook.enabled }}
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
            {{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
        {{- if .Values.webhook.enabled }}
        - name: cert
          secret:
            defaultMode: 420
            secretName: {{ include "elastic-operator.fullname" . }}-webhook-server-cert
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
